name: Primeiro Exemplo de CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
         run: echo este é um primeiro exemplo
      - name: Run a multi-line script
         run: |
          echo outras ações a executar
          echo testar o projecto.
