name: PipelineMVC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./GitHubActions
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./GitHubActions
      
  tests:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: dotnet test
      - working-directory: ./GitHubActions
