name: PipelineMVC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./GitHubActions
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./GitHubActions
    - name: unit testing
      run: dotnet test
      working-directory: ./GitHubActions
    - name: XUnit Viewer
      uses: AutoModality/action-xunit-viewer@v1.0.1
      with:
        if: always()
        name: test output
        path: artifacts/test
        
